function AppMeasurement_Module_AudienceManagement(d){var a=this;a.s=d;var b=window;b.s_c_in||(b.s_c_il=[],b.s_c_in=0);a._il=b.s_c_il;a._in=b.s_c_in;a._il[a._in]=a;b.s_c_in++;a._c="s_m";a.setup=function(c){b.DIL&&c&&(c.disableDefaultRequest=!0,c.disableScriptAttachment=!0,c.disableCORS=!0,c.secureDataCollection=!1,a.instance=b.DIL.create(c),a.tools=b.DIL.tools)};a.isReady=function(){return a.instance?!0:!1};a.getEventCallConfigParams=function(){return a.instance&&a.instance.api&&a.instance.api.getEventCallConfigParams?
a.instance.api.getEventCallConfigParams():{}};a.passData=function(b){a.instance&&a.instance.api&&a.instance.api.passData&&a.instance.api.passData(b)}}
"function"!==typeof window.DIL&&(window.DIL=function(a,c){var b=[],d,f;a!==Object(a)&&(a={});var g,k,r,v,s,p,n,E,u,A,L,B,C,F;g=a.partner;k=a.containerNSID;r=!!a.disableDestinationPublishingIframe;v=a.iframeAkamaiHTTPS;s=a.mappings;p=a.uuidCookie;n=!0===a.enableErrorReporting;E=a.visitorService;u=a.declaredId;A=!0===a.removeFinishedScriptsAndCallbacks;L=!0===a.delayAllUntilWindowLoad;B=!0===a.disableIDSyncs;C="undefined"===typeof a.secureDataCollection||!0===a.secureDataCollection;F=!0===a.useCORSOnly;
var M,N,I,G,O,P,Q,R;M=!0===a.disableScriptAttachment;N=!0===a.disableDefaultRequest;I=a.afterResultForDefaultRequest;G=a.dpIframeSrc;O=!0===a.testCORS;P=!0===a.useJSONPOnly;Q=a.visitorConstructor;R=!0===a.disableCORS;n&&DIL.errorModule.activate();var T=!0===window._dil_unit_tests;(d=c)&&b.push(d+"");if(!g||"string"!==typeof g)return d="DIL partner is invalid or not specified in initConfig",DIL.errorModule.handleError({name:"error",message:d,filename:"dil.js"}),Error(d);d="DIL containerNSID is invalid or not specified in initConfig, setting to default of 0";
if(k||"number"===typeof k)k=parseInt(k,10),!isNaN(k)&&0<=k&&(d="");d&&(k=0,b.push(d),d="");f=DIL.getDil(g,k);if(f instanceof DIL&&f.api.getPartner()===g&&f.api.getContainerNSID()===k)return f;if(this instanceof DIL)DIL.registerDil(this,g,k);else return new DIL(a,"DIL was not instantiated with the 'new' operator, returning a valid instance with partner = "+g+" and containerNSID = "+k);var z={IS_HTTPS:C||"https:"===document.location.protocol,POST_MESSAGE_ENABLED:!!window.postMessage,COOKIE_MAX_EXPIRATION_DATE:"Tue, 19 Jan 2038 03:14:07 UTC"},
J={stuffed:{}},m={},q={firingQueue:[],fired:[],firing:!1,sent:[],errored:[],reservedKeys:{sids:!0,pdata:!0,logdata:!0,callback:!0,postCallbackFn:!0,useImageRequest:!0},callbackPrefix:"demdexRequestCallback",firstRequestHasFired:!1,useJSONP:!0,abortRequests:!1,num_of_jsonp_responses:0,num_of_jsonp_errors:0,num_of_cors_responses:0,num_of_cors_errors:0,corsErrorSources:[],num_of_img_responses:0,num_of_img_errors:0,toRemove:[],removed:[],readyToRemove:!1,platformParams:{d_nsid:k+"",d_rtbd:"json",d_jsonv:DIL.jsonVersion+
"",d_dst:"1"},nonModStatsParams:{d_rtbd:!0,d_dst:!0,d_cts:!0,d_rs:!0},modStatsParams:null,adms:{TIME_TO_CATCH_ALL_REQUESTS_RELEASE:2E3,calledBack:!1,mid:null,noVisitorAPI:!1,VisitorAPI:null,instance:null,releaseType:"no VisitorAPI",isOptedOut:!0,isOptedOutCallbackCalled:!1,admsProcessingStarted:!1,process:function(e){try{if(!this.admsProcessingStarted){this.admsProcessingStarted=!0;var x=this,a,h,d,b;if("function"===typeof e&&"function"===typeof e.getInstance){if(E===Object(E)&&(a=E.namespace)&&"string"===
typeof a)h=e.getInstance(a,{idSyncContainerID:k});else{this.releaseType="no namespace";this.releaseRequests();return}if(h===Object(h)&&h instanceof e&&"function"===typeof h.isAllowed&&"function"===typeof h.getMarketingCloudVisitorID&&"function"===typeof h.getCustomerIDs&&"function"===typeof h.isOptedOut){this.VisitorAPI=e;if(!h.isAllowed()){this.releaseType="VisitorAPI not allowed";this.releaseRequests();return}this.instance=h;d=function(e){"VisitorAPI"!==x.releaseType&&(x.mid=e,x.releaseType="VisitorAPI",
x.releaseRequests())};b=h.getMarketingCloudVisitorID(d);if("string"===typeof b&&b.length){d(b);return}setTimeout(function(){"VisitorAPI"!==x.releaseType&&(x.releaseType="timeout",x.releaseRequests())},this.TIME_TO_CATCH_ALL_REQUESTS_RELEASE);return}this.releaseType="invalid instance"}else this.noVisitorAPI=!0;this.releaseRequests()}}catch(c){this.releaseRequests()}},releaseRequests:function(){this.calledBack=!0;q.registerRequest()},getMarketingCloudVisitorID:function(){return this.instance?this.instance.getMarketingCloudVisitorID():
null},getMIDQueryString:function(){var e=w.isPopulatedString,x=this.getMarketingCloudVisitorID();e(this.mid)&&this.mid===x||(this.mid=x);return e(this.mid)?"d_mid="+this.mid+"&":""},getCustomerIDs:function(){return this.instance?this.instance.getCustomerIDs():null},getCustomerIDsQueryString:function(e){if(e===Object(e)){var x="",a=[],h=[],d,b;for(d in e)e.hasOwnProperty(d)&&(h[0]=d,b=e[d],b===Object(b)&&(h[1]=b.id||"",h[2]=b.authState||0,a.push(h),h=[]));if(h=a.length)for(e=0;e<h;e++)x+="&d_cid_ic="+
t.encodeAndBuildRequest(a[e],"%01");return x}return""},getIsOptedOut:function(){this.instance?this.instance.isOptedOut([this,this.isOptedOutCallback],this.VisitorAPI.OptOut.GLOBAL,!0):(this.isOptedOut=!1,this.isOptedOutCallbackCalled=!0)},isOptedOutCallback:function(e){this.isOptedOut=e;this.isOptedOutCallbackCalled=!0;q.registerRequest()}},declaredId:{declaredId:{init:null,request:null},declaredIdCombos:{},setDeclaredId:function(e,a){var l=w.isPopulatedString,h=encodeURIComponent;if(e===Object(e)&&
l(a)){var d=e.dpid,b=e.dpuuid,c=null;if(l(d)&&l(b)){c=h(d)+"$"+h(b);if(!0===this.declaredIdCombos[c])return"setDeclaredId: combo exists for type '"+a+"'";this.declaredIdCombos[c]=!0;this.declaredId[a]={dpid:d,dpuuid:b};return"setDeclaredId: succeeded for type '"+a+"'"}}return"setDeclaredId: failed for type '"+a+"'"},getDeclaredIdQueryString:function(){var e=this.declaredId.request,a=this.declaredId.init,l=encodeURIComponent,h="";null!==e?h="&d_dpid="+l(e.dpid)+"&d_dpuuid="+l(e.dpuuid):null!==a&&(h=
"&d_dpid="+l(a.dpid)+"&d_dpuuid="+l(a.dpuuid));return h}},registerRequest:function(e){var a=this.firingQueue;e===Object(e)&&a.push(e);this.firing||!a.length||L&&!DIL.windowLoaded||(this.adms.isOptedOutCallbackCalled||this.adms.getIsOptedOut(),this.adms.calledBack&&!this.adms.isOptedOut&&this.adms.isOptedOutCallbackCalled&&(this.adms.isOptedOutCallbackCalled=!1,e=a.shift(),e.src=e.src.replace(/demdex.net\/event\?d_nsid=/,"demdex.net/event?"+this.adms.getMIDQueryString()+"d_nsid="),w.isPopulatedString(e.corsPostData)&&
(e.corsPostData=e.corsPostData.replace(/^d_nsid=/,this.adms.getMIDQueryString()+"d_nsid=")),D.fireRequest(e),this.firstRequestHasFired||"script"!==e.tag&&"cors"!==e.tag||(this.firstRequestHasFired=!0)))},processVisitorAPI:function(){this.adms.process(Q||window.Visitor)},requestRemoval:function(e){if(!A)return"removeFinishedScriptsAndCallbacks is not boolean true";var a=this.toRemove,l,h;e===Object(e)&&(l=e.script,h=e.callbackName,(l===Object(l)&&"SCRIPT"===l.nodeName||"no script created"===l)&&"string"===
typeof h&&h.length&&a.push(e));if(this.readyToRemove&&a.length){h=a.shift();l=h.script;h=h.callbackName;"no script created"!==l?(e=l.src,l.parentNode.removeChild(l)):e=l;window[h]=null;try{delete window[h]}catch(d){}this.removed.push({scriptSrc:e,callbackName:h});DIL.variables.scriptsRemoved.push(e);DIL.variables.callbacksRemoved.push(h);return this.requestRemoval()}return"requestRemoval() processed"}};f=function(){var e="http://fast.",a="?d_nsid="+k+"#"+encodeURIComponent(document.location.href);
if("string"===typeof G&&G.length)return G+a;z.IS_HTTPS&&(e=!0===v?"https://fast.":"https://");return e+g+".demdex.net/dest5.html"+a};var y={THROTTLE_START:3E4,throttleTimerSet:!1,id:"destination_publishing_iframe_"+g+"_"+k,url:f(),iframe:null,iframeHasLoaded:!1,sendingMessages:!1,messages:[],messagesPosted:[],messageSendingInterval:z.POST_MESSAGE_ENABLED?15:100,ibsDeleted:[],jsonProcessed:[],newIframeCreated:null,iframeIdChanged:!1,originalIframeHasLoadedAlready:null,attachIframe:function(){function e(){h=
document.createElement("iframe");h.sandbox="allow-scripts allow-same-origin";h.title="Adobe ID Syncing iFrame";h.id=l.id;h.style.cssText="display: none; width: 0; height: 0;";h.src=l.url;l.newIframeCreated=!0;a();document.body.appendChild(h)}function a(){t.addListener(h,"load",function(){h.className="aamIframeLoaded";l.iframeHasLoaded=!0;l.requestToProcess()})}var l=this,h=document.getElementById(this.id);h?"IFRAME"!==h.nodeName?(this.id+="_2",this.iframeIdChanged=!0,e()):(this.newIframeCreated=!1,
"aamIframeLoaded"!==h.className?(this.originalIframeHasLoadedAlready=!1,a()):(this.iframeHasLoaded=this.originalIframeHasLoadedAlready=!0,this.iframe=h,this.requestToProcess())):e();this.iframe=h},requestToProcess:function(e,a){var l=this;e&&!w.isEmptyObject(e)&&this.process(e,a);this.iframeHasLoaded&&this.messages.length&&!this.sendingMessages&&(this.throttleTimerSet||(this.throttleTimerSet=!0,setTimeout(function(){l.messageSendingInterval=z.POST_MESSAGE_ENABLED?15:150},this.THROTTLE_START)),this.sendingMessages=
!0,this.sendMessages())},process:function(e,a){var l=encodeURIComponent,h,d,b,c,g,f;a===Object(a)&&(f=t.encodeAndBuildRequest(["",a.dpid||"",a.dpuuid||""],","));if((h=e.dests)&&h instanceof Array&&(d=h.length))for(b=0;b<d;b++)c=h[b],c=[l("dests"),l(c.id||""),l(c.y||""),l(c.c||"")],this.addMessage(c.join("|"));if((h=e.ibs)&&h instanceof Array&&(d=h.length))for(b=0;b<d;b++)c=h[b],c=[l("ibs"),l(c.id||""),l(c.tag||""),t.encodeAndBuildRequest(c.url||[],","),l(c.ttl||""),"",f],this.addMessage(c.join("|"));
if((h=e.dpcalls)&&h instanceof Array&&(d=h.length))for(b=0;b<d;b++)c=h[b],g=c.callback||{},g=[g.obj||"",g.fn||"",g.key||"",g.tag||"",g.url||""],c=[l("dpm"),l(c.id||""),l(c.tag||""),t.encodeAndBuildRequest(c.url||[],","),l(c.ttl||""),t.encodeAndBuildRequest(g,","),f],this.addMessage(c.join("|"));this.jsonProcessed.push(e)},addMessage:function(e){var a=encodeURIComponent,a=n?a("---destpub-debug---"):a("---destpub---");this.messages.push(a+e)},sendMessages:function(){var e=this,a;this.messages.length?
(a=this.messages.shift(),DIL.xd.postMessage(a,this.url,this.iframe.contentWindow),this.messagesPosted.push(a),setTimeout(function(){e.sendMessages()},this.messageSendingInterval)):this.sendingMessages=!1}},K={traits:function(e){w.isValidPdata(e)&&(m.sids instanceof Array||(m.sids=[]),t.extendArray(m.sids,e));return this},pixels:function(e){w.isValidPdata(e)&&(m.pdata instanceof Array||(m.pdata=[]),t.extendArray(m.pdata,e));return this},logs:function(e){w.isValidLogdata(e)&&(m.logdata!==Object(m.logdata)&&
(m.logdata={}),t.extendObject(m.logdata,e));return this},customQueryParams:function(e){w.isEmptyObject(e)||t.extendObject(m,e,q.reservedKeys);return this},signals:function(e,a){var l,h=e;if(!w.isEmptyObject(h)){if(a&&"string"===typeof a)for(l in h={},e)e.hasOwnProperty(l)&&(h[a+l]=e[l]);t.extendObject(m,h,q.reservedKeys)}return this},declaredId:function(e){q.declaredId.setDeclaredId(e,"request");return this},result:function(e){"function"===typeof e&&(m.callback=e);return this},afterResult:function(e){"function"===
typeof e&&(m.postCallbackFn=e);return this},useImageRequest:function(){m.useImageRequest=!0;return this},clearData:function(){m={};return this},submit:function(){D.submitRequest(m);m={};return this},getPartner:function(){return g},getContainerNSID:function(){return k},getEventLog:function(){return b},getState:function(){var e={},b={};t.extendObject(e,q,{callbackPrefix:!0,useJSONP:!0,registerRequest:!0});t.extendObject(b,y,{attachIframe:!0,requestToProcess:!0,process:!0,sendMessages:!0});return{initConfig:a,
pendingRequest:m,otherRequestInfo:e,destinationPublishingInfo:b}},idSync:function(e){if(B)return"Error: id syncs have been disabled";if(e!==Object(e)||"string"!==typeof e.dpid||!e.dpid.length)return"Error: config or config.dpid is empty";if("string"!==typeof e.url||!e.url.length)return"Error: config.url is empty";var a=e.url,b=e.minutesToLive,h=encodeURIComponent,d,a=a.replace(/^https:/,"").replace(/^http:/,"");if("undefined"===typeof b)b=20160;else if(b=parseInt(b,10),isNaN(b)||0>=b)return"Error: config.minutesToLive needs to be a positive number";
d=t.encodeAndBuildRequest(["",e.dpid,e.dpuuid||""],",");e=["ibs",h(e.dpid),"img",h(a),b,"",d];y.addMessage(e.join("|"));q.firstRequestHasFired&&y.requestToProcess();return"Successfully queued"},aamIdSync:function(e){if(B)return"Error: id syncs have been disabled";if(e!==Object(e)||"string"!==typeof e.dpuuid||!e.dpuuid.length)return"Error: config or config.dpuuid is empty";e.url="//dpm.demdex.net/ibs:dpid="+e.dpid+"&dpuuid="+e.dpuuid;return this.idSync(e)},passData:function(e){if(w.isEmptyObject(e))return"Error: json is empty or not an object";
y.ibsDeleted.push(e.ibs);delete e.ibs;D.defaultCallback(e);return e},getPlatformParams:function(){return q.platformParams},getEventCallConfigParams:function(){var e=q,a=e.modStatsParams,b=e.platformParams,h;if(!a){a={};for(h in b)b.hasOwnProperty(h)&&!e.nonModStatsParams[h]&&(a[h.replace(/^d_/,"")]=b[h]);e.modStatsParams=a}return a}},D={corsMetadata:function(){var e="none",a=!0;"undefined"!==typeof XMLHttpRequest&&XMLHttpRequest===Object(XMLHttpRequest)&&("withCredentials"in new XMLHttpRequest?e=
"XMLHttpRequest":(new Function("/*@cc_on return /^10/.test(@_jscript_version) @*/"))()?e="XMLHttpRequest":"undefined"!==typeof XDomainRequest&&XDomainRequest===Object(XDomainRequest)&&(a=!1),0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")&&(a=!1));return{corsType:e,corsCookiesEnabled:a}}(),getCORSInstance:function(){return"none"===this.corsMetadata.corsType?null:new window[this.corsMetadata.corsType]},submitRequest:function(e){q.registerRequest(D.createQueuedRequest(e));
return!0},createQueuedRequest:function(e){var a=q,b,h=e.callback,d="img",c;if(!w.isEmptyObject(s)){var g,f,p;for(g in s)s.hasOwnProperty(g)&&(f=s[g],null!=f&&""!==f&&g in e&&!(f in e||f in q.reservedKeys)&&(p=e[g],null!=p&&""!==p&&(e[f]=p)))}w.isValidPdata(e.sids)||(e.sids=[]);w.isValidPdata(e.pdata)||(e.pdata=[]);w.isValidLogdata(e.logdata)||(e.logdata={});e.logdataArray=t.convertObjectToKeyValuePairs(e.logdata,"=",!0);e.logdataArray.push("_ts="+(new Date).getTime());"function"!==typeof h&&(h=this.defaultCallback);
a.useJSONP=!0!==e.useImageRequest;a.useJSONP&&(d="script",b=a.callbackPrefix+"_"+k+"_"+(new Date).getTime());a=this.makeRequestSrcData(e,b);P&&!F||!(c=this.getCORSInstance())||(d="cors");return{tag:d,src:a.src,corsSrc:a.corsSrc,internalCallbackName:b,callbackFn:h,postCallbackFn:e.postCallbackFn,useImageRequest:!!e.useImageRequest,requestData:e,corsInstance:c,corsPostData:a.corsPostData}},defaultCallback:function(e,a){var b,h,d,c,g,f,k,u,n;if((b=e.stuff)&&b instanceof Array&&(h=b.length))for(d=0;d<
h;d++)if((c=b[d])&&c===Object(c)){g=c.cn;f=c.cv;k=c.ttl;if("undefined"===typeof k||""===k)k=Math.floor(t.getMaxCookieExpiresInMinutes()/60/24);u=c.dmn||"."+document.domain.replace(/^www\./,"");n=c.type;g&&(f||"number"===typeof f)&&("var"!==n&&(k=parseInt(k,10))&&!isNaN(k)&&t.setCookie(g,f,1440*k,"/",u,!1),J.stuffed[g]=f)}b=e.uuid;w.isPopulatedString(b)&&!w.isEmptyObject(p)&&(h=p.path,"string"===typeof h&&h.length||(h="/"),d=parseInt(p.days,10),isNaN(d)&&(d=100),t.setCookie(p.name||"aam_did",b,1440*
d,h,p.domain||"."+document.domain.replace(/^www\./,""),!0===p.secure));r||q.abortRequests||y.requestToProcess(e,a)},makeRequestSrcData:function(e,a){e.sids=w.removeEmptyArrayValues(e.sids||[]);e.pdata=w.removeEmptyArrayValues(e.pdata||[]);var b=q,h=b.platformParams,d=t.encodeAndBuildRequest(e.sids,","),c=t.encodeAndBuildRequest(e.pdata,","),f=(e.logdataArray||[]).join("&");delete e.logdataArray;var p=z.IS_HTTPS?"https://":"http://",u=b.declaredId.getDeclaredIdQueryString(),n=b.adms.instance?b.adms.getCustomerIDsQueryString(b.adms.getCustomerIDs()):
"",s;s=[];var m,r,v,A;for(m in e)if(!(m in b.reservedKeys)&&e.hasOwnProperty(m))if(r=e[m],m=encodeURIComponent(m),r instanceof Array)for(v=0,A=r.length;v<A;v++)s.push(m+"="+encodeURIComponent(r[v]));else s.push(m+"="+encodeURIComponent(r));s=s.length?"&"+s.join("&"):"";d="d_nsid="+h.d_nsid+u+n+(d.length?"&d_sid="+d:"")+(c.length?"&d_px="+c:"")+(f.length?"&d_ld="+encodeURIComponent(f):"");h="&d_rtbd="+h.d_rtbd+"&d_jsonv="+h.d_jsonv+"&d_dst="+h.d_dst;p=p+g+".demdex.net/event";c=b=p+"?"+d+(b.useJSONP?
h+"&d_cb="+(a||""):"")+s;2048<b.length&&(b=b.substring(0,2048).substring(0,b.lastIndexOf("&")));return{corsSrc:p+"?"+(O?"testcors=1&d_nsid="+k+"&":"")+"_ts="+(new Date).getTime(),src:b,originalSrc:c,corsPostData:d+h+s,isDeclaredIdCall:""!==u}},fireRequest:function(e){if("img"===e.tag)this.fireImage(e);else{var a=q.declaredId,a=a.declaredId.request||a.declaredId.init||{},a={dpid:a.dpid||"",dpuuid:a.dpuuid||""};"script"===e.tag?this.fireScript(e,a):"cors"===e.tag&&this.fireCORS(e,a)}},fireImage:function(e){var a=
q,c,h;a.abortRequests||(a.firing=!0,c=new Image(0,0),a.sent.push(e),c.onload=function(){a.firing=!1;a.fired.push(e);a.num_of_img_responses++;a.registerRequest()},h=function(c){d="imgAbortOrErrorHandler received the event of type "+c.type;b.push(d);a.abortRequests=!0;a.firing=!1;a.errored.push(e);a.num_of_img_errors++;a.registerRequest()},c.addEventListener?(c.addEventListener("error",h,!1),c.addEventListener("abort",h,!1)):c.attachEvent&&(c.attachEvent("onerror",h),c.attachEvent("onabort",h)),c.src=
e.src)},fireScript:function(a,c){var f=this,h=q,k,p,u=a.src,n=a.postCallbackFn,s="function"===typeof n,m=a.internalCallbackName;h.abortRequests||(h.firing=!0,window[m]=function(f){try{f!==Object(f)&&(f={});B&&(y.ibsDeleted.push(f.ibs),delete f.ibs);var l=a.callbackFn;h.firing=!1;h.fired.push(a);h.num_of_jsonp_responses++;l(f,c);s&&n(f,c)}catch(k){k.message="DIL jsonp callback caught error with message "+k.message;d=k.message;b.push(d);k.filename=k.filename||"dil.js";k.partner=g;DIL.errorModule.handleError(k);
try{l({error:k.name+"|"+k.message},c),s&&n({error:k.name+"|"+k.message},c)}catch(u){}}finally{h.requestRemoval({script:p,callbackName:m}),h.registerRequest()}},M||F?(h.firing=!1,h.requestRemoval({script:"no script created",callbackName:m})):(p=document.createElement("script"),p.addEventListener&&p.addEventListener("error",function(b){h.requestRemoval({script:p,callbackName:m});d="jsonp script tag error listener received the event of type "+b.type+" with src "+u;f.handleScriptError(d,a)},!1),p.type=
"text/javascript",p.src=u,k=DIL.variables.scriptNodeList[0],k.parentNode.insertBefore(p,k)),h.sent.push(a),h.declaredId.declaredId.request=null)},fireCORS:function(a,c){var f=this,h=q,k=this.corsMetadata.corsType,p=a.corsSrc,u=a.corsInstance,n=a.corsPostData,s=a.postCallbackFn,m="function"===typeof s;if(!h.abortRequests&&!R){h.firing=!0;try{u.open("post",p,!0),"XMLHttpRequest"===k&&(u.withCredentials=!0,u.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),u.onreadystatechange=function(){if(4===
this.readyState&&200===this.status)a:{var k;try{if(k=JSON.parse(this.responseText),k!==Object(k)){f.handleCORSError(a,c,"Response is not JSON");break a}}catch(p){f.handleCORSError(a,c,"Error parsing response as JSON");break a}B&&(y.ibsDeleted.push(k.ibs),delete k.ibs);try{var u=a.callbackFn;h.firing=!1;h.fired.push(a);h.num_of_cors_responses++;u(k,c);m&&s(k,c)}catch(n){n.message="DIL handleCORSResponse caught error with message "+n.message;d=n.message;b.push(d);n.filename=n.filename||"dil.js";n.partner=
g;DIL.errorModule.handleError(n);try{u({error:n.name+"|"+n.message},c),m&&s({error:n.name+"|"+n.message},c)}catch(q){}}finally{h.registerRequest()}}}),u.onerror=function(){f.handleCORSError(a,c,"onerror")},u.ontimeout=function(){f.handleCORSError(a,c,"ontimeout")},u.send(n)}catch(r){this.handleCORSError(a,c,"try-catch")}h.sent.push(a);h.declaredId.declaredId.request=null}},handleCORSError:function(a,b,c){q.num_of_cors_errors++;q.corsErrorSources.push(c);"ontimeout"===c||F||(a.tag="script",this.fireScript(a,
b))},handleScriptError:function(a,b){q.num_of_jsonp_errors++;this.handleRequestError(a,b)},handleRequestError:function(a,c){var d=q;b.push(a);d.abortRequests=!0;d.firing=!1;d.errored.push(c);d.registerRequest()}},w={isValidPdata:function(a){return a instanceof Array&&this.removeEmptyArrayValues(a).length?!0:!1},isValidLogdata:function(a){return!this.isEmptyObject(a)},isEmptyObject:function(a){if(a!==Object(a))return!0;for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},removeEmptyArrayValues:function(a){for(var b=
0,c=a.length,d,f=[],b=0;b<c;b++)d=a[b],"undefined"!==typeof d&&null!==d&&""!==d&&f.push(d);return f},isPopulatedString:function(a){return"string"===typeof a&&a.length}},t={addListener:function(){if(document.addEventListener)return function(a,b,c){a.addEventListener(b,function(a){"function"===typeof c&&c(a)},!1)};if(document.attachEvent)return function(a,b,c){a.attachEvent("on"+b,function(a){"function"===typeof c&&c(a)})}}(),convertObjectToKeyValuePairs:function(a,b,c){var d=[],f,g;b||(b="=");for(f in a)a.hasOwnProperty(f)&&
(g=a[f],"undefined"!==typeof g&&null!==g&&""!==g&&d.push(f+b+(c?encodeURIComponent(g):g)));return d},encodeAndBuildRequest:function(a,b){return this.map(a,function(a){return encodeURIComponent(a)}).join(b)},map:function(a,b){if(Array.prototype.map)return a.map(b);if(void 0===a||null===a)throw new TypeError;var c=Object(a),d=c.length>>>0;if("function"!==typeof b)throw new TypeError;for(var f=Array(d),g=0;g<d;g++)g in c&&(f[g]=b.call(b,c[g],g,c));return f},filter:function(a,b){if(!Array.prototype.filter){if(void 0===
a||null===a)throw new TypeError;var c=Object(a),d=c.length>>>0;if("function"!==typeof b)throw new TypeError;for(var f=[],g=0;g<d;g++)if(g in c){var k=c[g];b.call(b,k,g,c)&&f.push(k)}return f}return a.filter(b)},getCookie:function(a){a+="=";var b=document.cookie.split(";"),c,d,f;c=0;for(d=b.length;c<d;c++){for(f=b[c];" "===f.charAt(0);)f=f.substring(1,f.length);if(0===f.indexOf(a))return decodeURIComponent(f.substring(a.length,f.length))}return null},setCookie:function(a,b,c,d,f,g){var k=new Date;
c&&(c*=6E4);document.cookie=a+"="+encodeURIComponent(b)+(c?";expires="+(new Date(k.getTime()+c)).toUTCString():"")+(d?";path="+d:"")+(f?";domain="+f:"")+(g?";secure":"")},extendArray:function(a,b){return a instanceof Array&&b instanceof Array?(Array.prototype.push.apply(a,b),!0):!1},extendObject:function(a,b,c){var d;if(a===Object(a)&&b===Object(b)){for(d in b)!b.hasOwnProperty(d)||!w.isEmptyObject(c)&&d in c||(a[d]=b[d]);return!0}return!1},getMaxCookieExpiresInMinutes:function(){return((new Date(z.COOKIE_MAX_EXPIRATION_DATE)).getTime()-
(new Date).getTime())/1E3/60}};"error"===g&&0===k&&t.addListener(window,"load",function(){DIL.windowLoaded=!0});var S=!1,H=function(){S||(S=!0,q.registerRequest(),U(),r||q.abortRequests||y.attachIframe(),q.readyToRemove=!0,q.requestRemoval())},U=function(){r||setTimeout(function(){N||q.firstRequestHasFired||("function"===typeof I?K.afterResult(I).submit():K.submit())},DIL.constants.TIME_TO_DEFAULT_REQUEST)};C=document;"error"!==g&&(DIL.windowLoaded?H():"complete"!==C.readyState&&"loaded"!==C.readyState?
t.addListener(window,"load",function(){DIL.windowLoaded=!0;H()}):(DIL.windowLoaded=!0,H()));q.declaredId.setDeclaredId(u,"init");q.processVisitorAPI();this.api=K;this.getStuffedVariable=function(a){var b=J.stuffed[a];b||"number"===typeof b||(b=t.getCookie(a))||"number"===typeof b||(b="");return b};this.validators=w;this.helpers=t;this.constants=z;this.log=b;T&&(this.pendingRequest=m,this.requestController=q,this.setDestinationPublishingUrl=f,this.destinationPublishing=y,this.requestProcs=D,this.variables=
J,this.callWindowLoadFunctions=H)},function(){var a=document,c;null==a.readyState&&a.addEventListener&&(a.readyState="loading",a.addEventListener("DOMContentLoaded",c=function(){a.removeEventListener("DOMContentLoaded",c,!1);a.readyState="complete"},!1))}(),DIL.extendStaticPropertiesAndMethods=function(a){var c;if(a===Object(a))for(c in a)a.hasOwnProperty(c)&&(this[c]=a[c])},DIL.extendStaticPropertiesAndMethods({version:"6.5",jsonVersion:1,constants:{TIME_TO_DEFAULT_REQUEST:50},variables:{scriptNodeList:document.getElementsByTagName("script"),
scriptsRemoved:[],callbacksRemoved:[]},windowLoaded:!1,dils:{},isAddedPostWindowLoad:function(a){this.windowLoaded="function"===typeof a?!!a():"boolean"===typeof a?a:!0},create:function(a){try{return new DIL(a)}catch(c){return(new Image(0,0)).src="http://error.demdex.net/event?d_nsid=0&d_px=14137&d_ld=name%3Derror%26filename%3Ddil.js%26partner%3Dno_partner%26message%3DError%2520in%2520attempt%2520to%2520create%2520DIL%2520instance%2520with%2520DIL.create()%26_ts%3D"+(new Date).getTime(),Error("Error in attempt to create DIL instance with DIL.create()")}},
registerDil:function(a,c,b){c=c+"$"+b;c in this.dils||(this.dils[c]=a)},getDil:function(a,c){var b;"string"!==typeof a&&(a="");c||(c=0);b=a+"$"+c;return b in this.dils?this.dils[b]:Error("The DIL instance with partner = "+a+" and containerNSID = "+c+" was not found")},dexGetQSVars:function(a,c,b){c=this.getDil(c,b);return c instanceof this?c.getStuffedVariable(a):""},xd:{postMessage:function(a,c,b){var d=1;c&&(window.postMessage?b.postMessage(a,c.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):c&&(b.location=
c.replace(/#.*$/,"")+"#"+ +new Date+d++ +"&"+a))}}}),DIL.errorModule=function(){var a=DIL.create({partner:"error",containerNSID:0,disableDestinationPublishingIframe:!0}),c={harvestererror:14138,destpuberror:14139,dpmerror:14140,generalerror:14137,error:14137,noerrortypedefined:15021,evalerror:15016,rangeerror:15017,referenceerror:15018,typeerror:15019,urierror:15020},b=!1;return{activate:function(){b=!0},handleError:function(d){if(!b)return"DIL error module has not been activated";d!==Object(d)&&
(d={});var f=d.name?(d.name+"").toLowerCase():"",g=[];d={name:f,filename:d.filename?d.filename+"":"",partner:d.partner?d.partner+"":"no_partner",site:d.site?d.site+"":document.location.href,message:d.message?d.message+"":""};g.push(f in c?c[f]:c.noerrortypedefined);a.api.pixels(g).logs(d).useImageRequest().submit();return"DIL error report sent"},pixelMap:c}}(),DIL.tools={},DIL.modules={helpers:{handleModuleError:function(a,c,b){var d="";c=c||"Error caught in DIL module/submodule: ";a===Object(a)?
d=c+(a.message||"err has no message"):(d=c+"err is not a valid object",a={});a.message=d;b instanceof DIL&&(a.partner=b.api.getPartner());DIL.errorModule.handleError(a);return this.errorMessage=d}}});
DIL.tools.getSearchReferrer=function(a,c){var b=DIL.getDil("error"),d=DIL.tools.decomposeURI(a||document.referrer),f="",g="",k={queryParam:"q"};return(f=b.helpers.filter([c===Object(c)?c:{},{hostPattern:/aol\./},{hostPattern:/ask\./},{hostPattern:/bing\./},{hostPattern:/google\./},{hostPattern:/yahoo\./,queryParam:"p"}],function(a){return!(!a.hasOwnProperty("hostPattern")||!d.hostname.match(a.hostPattern))}).shift())?{valid:!0,name:d.hostname,keywords:(b.helpers.extendObject(k,f),g=k.queryPattern?
(f=(""+d.search).match(k.queryPattern))?f[1]:"":d.uriParams[k.queryParam],decodeURIComponent(g||"").replace(/\+|%20/g," "))}:{valid:!1,name:"",keywords:""}};
DIL.tools.decomposeURI=function(a){var c=DIL.getDil("error"),b=document.createElement("a");b.href=a||document.referrer;return{hash:b.hash,host:b.host.split(":").shift(),hostname:b.hostname,href:b.href,pathname:b.pathname.replace(/^\//,""),protocol:b.protocol,search:b.search,uriParams:function(a,b){c.helpers.map(b.split("&"),function(b){b=b.split("=");a[b.shift()]=b.shift()});return a}({},b.search.replace(/^(\/|\?)?|\/$/g,""))}};
DIL.tools.getMetaTags=function(){var a={},c=document.getElementsByTagName("meta"),b,d,f,g,k;b=0;for(f=arguments.length;b<f;b++)if(g=arguments[b],null!==g)for(d=0;d<c.length;d++)if(k=c[d],k.name===g){a[g]=k.content;break}return a};
DIL.modules.siteCatalyst={dil:null,handle:DIL.modules.helpers.handleModuleError,init:function(a,c,b,d){try{var f=this,g={name:"DIL Site Catalyst Module Error"},k=function(a){g.message=a;DIL.errorModule.handleError(g);return a};this.options=d===Object(d)?d:{};this.dil=null;if(c instanceof DIL)this.dil=c;else return k("dilInstance is not a valid instance of DIL");g.partner=c.api.getPartner();if(a!==Object(a))return k("siteCatalystReportingSuite is not an object");window.AppMeasurement_Module_DIL=a.m_DIL=
function(a){var c="function"===typeof a.m_i?a.m_i("DIL"):this;if(c!==Object(c))return k("m is not an object");c.trackVars=f.constructTrackVars(b);c.d=0;c.s=a;c._t=function(){var a,b,c=","+this.trackVars+",",d=this.s,g,s=[];g=[];var r={},v=!1;if(d!==Object(d))return k("Error in m._t function: s is not an object");if(this.d){if("function"===typeof d.foreachVar)d.foreachVar(function(a,b){"undefined"!==typeof b&&(r[a]=b,v=!0)},this.trackVars);else{if(!(d.va_t instanceof Array))return k("Error in m._t function: s.va_t is not an array");
if(d.lightProfileID)(a=d.lightTrackVars)&&(a=","+a+","+d.vl_mr+",");else if(d.pe||d.linkType)a=d.linkTrackVars,d.pe&&(b=d.pe.substring(0,1).toUpperCase()+d.pe.substring(1),d[b]&&(a=d[b].trackVars)),a&&(a=","+a+","+d.vl_l+","+d.vl_l2+",");if(a){b=0;for(s=a.split(",");b<s.length;b++)0<=c.indexOf(","+s[b]+",")&&g.push(s[b]);g.length&&(c=","+g.join(",")+",")}g=0;for(b=d.va_t.length;g<b;g++)a=d.va_t[g],0<=c.indexOf(","+a+",")&&"undefined"!==typeof d[a]&&null!==d[a]&&""!==d[a]&&(r[a]=d[a],v=!0)}f.includeContextData(d,
r).store_populated&&(v=!0);v&&this.d.api.signals(r,"c_").submit()}}};a.loadModule("DIL");a.DIL.d=c;return g.message?g.message:"DIL.modules.siteCatalyst.init() completed with no errors"}catch(r){return this.handle(r,"DIL.modules.siteCatalyst.init() caught error with message ",this.dil)}},constructTrackVars:function(a){var c=[],b,d,f,g,k;if(a===Object(a)){b=a.names;if(b instanceof Array&&(f=b.length))for(d=0;d<f;d++)g=b[d],"string"===typeof g&&g.length&&c.push(g);a=a.iteratedNames;if(a instanceof Array&&
(f=a.length))for(d=0;d<f;d++)if(b=a[d],b===Object(b)&&(g=b.name,k=parseInt(b.maxIndex,10),"string"===typeof g&&g.length&&!isNaN(k)&&0<=k))for(b=0;b<=k;b++)c.push(g+b);if(c.length)return c.join(",")}return this.constructTrackVars({names:"pageName channel campaign products events pe pev1 pev2 pev3".split(" "),iteratedNames:[{name:"prop",maxIndex:75},{name:"eVar",maxIndex:250}]})},includeContextData:function(a,c){var b={},d=!1;if(a.contextData===Object(a.contextData)){var f=a.contextData,g=this.options.replaceContextDataPeriodsWith,
k=this.options.filterFromContextVariables,r={},v,s,p,n;"string"===typeof g&&g.length||(g="_");if(k instanceof Array)for(v=0,s=k.length;v<s;v++)p=k[v],this.dil.validators.isPopulatedString(p)&&(r[p]=!0);for(n in f)!f.hasOwnProperty(n)||r[n]||!(k=f[n])&&"number"!==typeof k||(n=("contextData."+n).replace(/\./g,g),c[n]=k,d=!0)}b.store_populated=d;return b}};
DIL.modules.GA={dil:null,arr:null,tv:null,errorMessage:"",defaultTrackVars:["_setAccount","_setCustomVar","_addItem","_addTrans","_trackSocial"],defaultTrackVarsObj:null,signals:{},hasSignals:!1,handle:DIL.modules.helpers.handleModuleError,init:function(a,c,b){try{this.tv=this.arr=this.dil=null;this.errorMessage="";this.signals={};this.hasSignals=!1;var d={name:"DIL GA Module Error"},f="";c instanceof DIL?(this.dil=c,d.partner=this.dil.api.getPartner()):(f="dilInstance is not a valid instance of DIL",
d.message=f,DIL.errorModule.handleError(d));a instanceof Array&&a.length?this.arr=a:(f="gaArray is not an array or is empty",d.message=f,DIL.errorModule.handleError(d));this.tv=this.constructTrackVars(b);this.errorMessage=f}catch(g){this.handle(g,"DIL.modules.GA.init() caught error with message ",this.dil)}finally{return this}},constructTrackVars:function(a){var c=[],b,d,f,g;if(this.defaultTrackVarsObj!==Object(this.defaultTrackVarsObj)){f=this.defaultTrackVars;g={};b=0;for(d=f.length;b<d;b++)g[f[b]]=
!0;this.defaultTrackVarsObj=g}else g=this.defaultTrackVarsObj;if(a===Object(a)){a=a.names;if(a instanceof Array&&(d=a.length))for(b=0;b<d;b++)f=a[b],"string"===typeof f&&f.length&&f in g&&c.push(f);if(c.length)return c}return this.defaultTrackVars},constructGAObj:function(a){var c={};a=a instanceof Array?a:this.arr;var b,d,f,g;b=0;for(d=a.length;b<d;b++)f=a[b],f instanceof Array&&f.length&&(f=[],g=a[b],f instanceof Array&&g instanceof Array&&Array.prototype.push.apply(f,g),g=f.shift(),"string"===
typeof g&&g.length&&(c[g]instanceof Array||(c[g]=[]),c[g].push(f)));return c},addToSignals:function(a,c){if("string"!==typeof a||""===a||null==c||""===c)return!1;this.signals[a]instanceof Array||(this.signals[a]=[]);this.signals[a].push(c);return this.hasSignals=!0},constructSignals:function(){var a=this.constructGAObj(),c={_setAccount:function(a){this.addToSignals("c_accountId",a)},_setCustomVar:function(a,b,c){"string"===typeof b&&b.length&&this.addToSignals("c_"+b,c)},_addItem:function(a,b,c,d,
f,g){this.addToSignals("c_itemOrderId",a);this.addToSignals("c_itemSku",b);this.addToSignals("c_itemName",c);this.addToSignals("c_itemCategory",d);this.addToSignals("c_itemPrice",f);this.addToSignals("c_itemQuantity",g)},_addTrans:function(a,b,c,d,f,g,k,r){this.addToSignals("c_transOrderId",a);this.addToSignals("c_transAffiliation",b);this.addToSignals("c_transTotal",c);this.addToSignals("c_transTax",d);this.addToSignals("c_transShipping",f);this.addToSignals("c_transCity",g);this.addToSignals("c_transState",
k);this.addToSignals("c_transCountry",r)},_trackSocial:function(a,b,c,d){this.addToSignals("c_socialNetwork",a);this.addToSignals("c_socialAction",b);this.addToSignals("c_socialTarget",c);this.addToSignals("c_socialPagePath",d)}},b=this.tv,d,f,g,k,r,v;d=0;for(f=b.length;d<f;d++)if(g=b[d],a.hasOwnProperty(g)&&c.hasOwnProperty(g)&&(v=a[g],v instanceof Array))for(k=0,r=v.length;k<r;k++)c[g].apply(this,v[k])},submit:function(){try{if(""!==this.errorMessage)return this.errorMessage;this.constructSignals();
return this.hasSignals?(this.dil.api.signals(this.signals).submit(),"Signals sent: "+this.dil.helpers.convertObjectToKeyValuePairs(this.signals,"=",!0)+this.dil.log):"No signals present"}catch(a){return this.handle(a,"DIL.modules.GA.submit() caught error with message ",this.dil)}},Stuffer:{LIMIT:5,dil:null,cookieName:null,delimiter:null,errorMessage:"",handle:DIL.modules.helpers.handleModuleError,callback:null,v:function(){return!1},init:function(a,c,b){try{this.callback=this.dil=null,this.errorMessage=
"",a instanceof DIL?(this.dil=a,this.v=this.dil.validators.isPopulatedString,this.cookieName=this.v(c)?c:"aam_ga",this.delimiter=this.v(b)?b:"|"):this.handle({message:"dilInstance is not a valid instance of DIL"},"DIL.modules.GA.Stuffer.init() error: ")}catch(d){this.handle(d,"DIL.modules.GA.Stuffer.init() caught error with message ",this.dil)}finally{return this}},process:function(a){var c,b,d,f,g,k;k=!1;var r=1;if(a===Object(a)&&(c=a.stuff)&&c instanceof Array&&(b=c.length))for(a=0;a<b;a++)if((d=
c[a])&&d===Object(d)&&(f=d.cn,g=d.cv,f===this.cookieName&&this.v(g))){k=!0;break}if(k){c=g.split(this.delimiter);"undefined"===typeof window._gaq&&(window._gaq=[]);d=window._gaq;a=0;for(b=c.length;a<b&&!(k=c[a].split("="),g=k[0],k=k[1],this.v(g)&&this.v(k)&&d.push(["_setCustomVar",r++,g,k,1]),r>this.LIMIT);a++);this.errorMessage=1<r?"No errors - stuffing successful":"No valid values to stuff"}else this.errorMessage="Cookie name and value not found in json";if("function"===typeof this.callback)return this.callback()},
submit:function(){try{var a=this;if(""!==this.errorMessage)return this.errorMessage;this.dil.api.afterResult(function(b){a.process(b)}).submit();return"DIL.modules.GA.Stuffer.submit() successful"}catch(c){return this.handle(c,"DIL.modules.GA.Stuffer.submit() caught error with message ",this.dil)}}}};
DIL.modules.Peer39={aid:"",dil:null,optionals:null,errorMessage:"",calledBack:!1,script:null,scriptsSent:[],returnedData:[],handle:DIL.modules.helpers.handleModuleError,init:function(a,c,b){try{this.dil=null;this.errorMessage="";this.calledBack=!1;this.optionals=b===Object(b)?b:{};b={name:"DIL Peer39 Module Error"};var d=[],f="";this.isSecurePageButNotEnabled(document.location.protocol)&&(f="Module has not been enabled for a secure page",d.push(f),b.message=f,DIL.errorModule.handleError(b));c instanceof
DIL?(this.dil=c,b.partner=this.dil.api.getPartner()):(f="dilInstance is not a valid instance of DIL",d.push(f),b.message=f,DIL.errorModule.handleError(b));"string"===typeof a&&a.length?this.aid=a:(f="aid is not a string or is empty",d.push(f),b.message=f,DIL.errorModule.handleError(b));this.errorMessage=d.join("\n")}catch(g){this.handle(g,"DIL.modules.Peer39.init() caught error with message ",this.dil)}finally{return this}},isSecurePageButNotEnabled:function(a){return"https:"===a&&!0!==this.optionals.enableHTTPS?
!0:!1},constructSignals:function(){var a=this,c=this.constructScript(),b=DIL.variables.scriptNodeList[0];window["afterFinished_"+this.aid]=function(){try{var b=a.processData(p39_KVP_Short("c_p","|").split("|"));b.hasSignals&&a.dil.api.signals(b.signals).submit()}catch(c){}finally{a.calledBack=!0,"function"===typeof a.optionals.afterResult&&a.optionals.afterResult()}};b.parentNode.insertBefore(c,b);this.scriptsSent.push(c);return"Request sent to Peer39"},processData:function(a){var c,b,d,f,g={},k=
!1;this.returnedData.push(a);if(a instanceof Array)for(c=0,b=a.length;c<b;c++)d=a[c].split("="),f=d[0],d=d[1],f&&isFinite(d)&&!isNaN(parseInt(d,10))&&(g[f]instanceof Array||(g[f]=[]),g[f].push(d),k=!0);return{hasSignals:k,signals:g}},constructScript:function(){var a=document.createElement("script"),c=this.optionals,b=c.scriptId,d=c.scriptSrc,c=c.scriptParams;a.id="string"===typeof b&&b.length?b:"peer39ScriptLoader";a.type="text/javascript";"string"===typeof d&&d.length?a.src=d:(a.src=document.location.protocol+
"//stags.peer39.net/"+this.aid+"/trg_"+this.aid+".js","string"===typeof c&&c.length&&(a.src+="?"+c));return a},submit:function(){try{return""!==this.errorMessage?this.errorMessage:this.constructSignals()}catch(a){return this.handle(a,"DIL.modules.Peer39.submit() caught error with message ",this.dil)}}};
